{{- if .Values.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "lighthouse-stack.fullname" . }}-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "lighthouse-stack.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: http
  selector:
    {{- include "lighthouse-stack.matchLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
{{- end }}
